version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports: ['2181:2181']

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: ['zookeeper']
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports: ['29092:29092']

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotelpass
      POSTGRES_DB: reservation_command
    volumes: ['pgdata:/var/lib/postgresql/data']
    ports: ['5432:5432']

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  command-service:
    build: ./reservation-command-service
    depends_on: ['kafka','postgres']
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports: ['8081:8081']

  query-service:
    build: ./reservation-query-service
    depends_on:
      kafka:
        condition: service_started
      mongo:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_MONGODB_URI: mongodb://mongo:27017/reservation_query
    ports: [ '8082:8082' ]

  angular-ui:
    build: ./hotel-reservation-ui
    ports:
      - "4200:80"
    depends_on:
      - command-service
      - query-service


volumes:
  pgdata:
  mongodata:
