spring:
  application:
    name: reservation-query

  spring:
    mongodb:
      uri: mongodb://localhost:27017/reservation_query


server:
  port: 8082

kafka:
  bootstrap-servers: kafka:9092
  topic:
    reservation-events: hotel.reservation.events
