spring:
  mongodb:
    uri: mongodb://mongo:27017/reservation_query

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: reservation-query-v2
      auto-offset-reset: earliest

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

kafka:
  topic:
    reservation-events: hotel.reservation.events
